name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0  
    - name: rebuild
      run: autoreconf -i  
    - name: dependencies
      run: sudo apt install -y libldap2-dev  
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: plugin 
        # Directory containing files to upload
        path: .libs/flopsar-ldap.so
