name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0  
    - name: Rebuild configuration
      run: autoreconf -i  
    - name: Install dependencies
      run: sudo apt install -y libldap2-dev  
    - name: Configure
      run: ./configure
    - name: Build
      run: make
    - name: Deploy artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: plugin 
        path: .libs/flopsar-ldap.so
    - name: Release assets
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GHR_COMPRESS: zip
          GHR_PATH: .libs/flopsar-ldap.so
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
